"""
LLM-driven program builder.

Two-tier architecture (per the research writeup — May 2026):

  1) SPLIT PLANNER (1 LLM call)
       Input  : full UserProfile (goal, schedule, equipment, injuries,
                experience, calibration results)
       Output : list of DaySpec — name + target muscles + minutes per day
       Model  : reasoning-heavy (gpt-4o)
       The split planner never sees the catalog. It works in muscle/pattern
       space, not exercise space.

  2) EXERCISE PICKER (N LLM calls, one per day, parallelizable)
       Input  : DaySpec + server-pre-filtered candidate list (equipment +
                muscle + level — typically 30-60 names, far below OpenAI's
                1000-enum cap)
       Output : ordered list of catalog_name picks
       Model  : constrained-choice (gpt-4o or mini)
       The candidate list is an enum in the response schema — strict-mode
       structured output makes hallucinated exercise names impossible
       at decode time.

  3) VALIDATION (deterministic, post-LLM)
       Catches things the schema can't:
         - exercise's primary muscles actually match the day's targets
         - equipment is actually in the user's available set
         - no exercise picked twice in the same day
       Anything that fails validation is dropped. Empty days fall back to
       deterministic slot-ladder picks (the existing persona behavior).

Why two tiers, not one big call:
  - 873-name enum hits OpenAI's per-schema cap and bloats every prompt
  - per-day calls have small focused schemas the model handles well
  - each tier is independently testable and replaceable
  - server-side filtering means the LLM never sees obviously-wrong options
    (no "do barbell squats" when the user only has dumbbells)

Sets/reps/load are NOT generated by the LLM today — the existing persona
progression rules own that. Reason: numbers that drive load are where bad
programs hurt people. Earning the LLM's trust for those numbers is a separate
project from earning its trust for exercise selection.
"""

from __future__ import annotations

import json
import logging
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Literal

from pydantic import BaseModel, Field

from .exercises import Exercise, ExerciseCatalog, catalog as _default_catalog
from .llm import LLMClient
from .models import ExercisePrescription, Session, UserProfile


logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Output types — what the caller gets back. Plain Pydantic so callers can
# .model_dump() into JSON or write to the store without ceremony.
# ---------------------------------------------------------------------------


class ExercisePick(BaseModel):
    catalog_name: str           # validated to exist in catalog
    slot: str                   # "primary_compound", "secondary", "accessory_1", ...
    rationale: str              # one-sentence "why this one"


class DaySpec(BaseModel):
    """One day in the week — either training or recovery.

    Recovery days don't go through the exercise picker (no LLM call); they
    get a deterministic stretching/mobility block filled in by the renderer.
    The split planner decides whether a day is training vs. recovery; we
    don't second-guess it.
    """
    day_index: int                            # 1-based, position in the week
    kind: Literal["training", "recovery"] = "training"
    name: str                                 # "Chest + Triceps" / "Mobility & Stretch"
    primary_muscles: list[str]                # canonical names from the catalog
    secondary_muscles: list[str]
    target_minutes: int
    pattern_focus: str                        # "horizontal_push", "mobility", ...


class DayPlan(BaseModel):
    """A DaySpec filled in with picked exercises."""
    spec: DaySpec
    exercises: list[ExercisePick]


class WeekSplit(BaseModel):
    days: list[DaySpec]
    rationale: str              # the LLM's one-paragraph "why this split"


class ValidationIssue(BaseModel):
    day_index: int
    catalog_name: str
    issue: str                  # "muscle_mismatch" | "equipment_unavailable" | "not_in_catalog" | "duplicate"


class AIProgram(BaseModel):
    split: WeekSplit
    days: list[DayPlan]
    issues: list[ValidationIssue] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Canonical muscle vocabulary — the dataset uses these strings. We hand them
# to the LLM as an enum in the split-planner schema so the planner can't
# invent a muscle name the picker won't recognize. Order matches catalog
# usage frequency.
# ---------------------------------------------------------------------------

CANONICAL_MUSCLES = [
    "chest", "shoulders", "triceps", "biceps", "forearms",
    "lats", "middle back", "lower back", "traps", "neck",
    "abdominals", "obliques",
    "quadriceps", "hamstrings", "glutes", "calves",
    "adductors", "abductors",
    "cardiovascular system",
]


# ---------------------------------------------------------------------------
# Split planner — Call 1.
# ---------------------------------------------------------------------------


def _split_planner_schema(min_days: int, max_days: int) -> dict[str, Any]:
    """JSON schema for OpenAI strict structured output, split-planner shape.

    `min_days`/`max_days` is the TOTAL day count (training + recovery
    combined). The prompt teaches the LLM how many of each. We don't try
    to express "exactly N training days AND M recovery days" in the schema
    because that's a quantitative cross-field constraint JSON schema can't
    express cleanly — we verify it in code after.
    """
    day_schema = {
        "type": "object",
        "additionalProperties": False,
        "required": ["day_index", "kind", "name", "primary_muscles",
                     "secondary_muscles", "target_minutes", "pattern_focus"],
        "properties": {
            "day_index": {"type": "integer", "minimum": 1, "maximum": 7},
            "kind": {"type": "string", "enum": ["training", "recovery"]},
            "name": {"type": "string"},
            "primary_muscles": {
                "type": "array",
                "items": {"type": "string", "enum": CANONICAL_MUSCLES},
            },
            "secondary_muscles": {
                "type": "array",
                "items": {"type": "string", "enum": CANONICAL_MUSCLES},
            },
            "target_minutes": {"type": "integer", "minimum": 10, "maximum": 180},
            "pattern_focus": {"type": "string"},
        },
    }
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["days", "rationale"],
        "properties": {
            "days": {
                "type": "array",
                "items": day_schema,
                "minItems": min_days,
                "maxItems": max_days,
            },
            "rationale": {"type": "string"},
        },
    }


def _profile_for_llm(profile: UserProfile) -> dict[str, Any]:
    """The compact, structured slice of the profile the LLM sees.

    Strip user_id and timestamps — they're noise to the model. Include
    answers (raw intake) AND derived (LLM-extracted structured fields)
    because they disagree often enough that both signals are useful.
    """
    return {
        "goal_domain": profile.domain,
        "intake_answers": profile.answers,
        "derived_profile": profile.derived,
    }


SPLIT_PLANNER_SYSTEM = """\
You are a strength-and-conditioning coach planning a weekly split.

You will be given a user profile (goal, schedule, equipment, injuries,
experience, calibration results, preferences). Return a list of DAYS for
the week. Each day is either:

  - kind="training" — muscle/pattern targets, time budget. Goes to the
    exercise picker downstream.
  - kind="recovery" — active recovery / mobility / stretching. Use
    primary_muscles=["abdominals"] or similar (schema needs SOMETHING; it
    won't be used). pattern_focus should describe the recovery intent
    (e.g. "mobility", "stretch_hips_shoulders", "easy_walk").

You do NOT pick exercises in this step — downstream calls do that. Stay in
muscle/pattern space. Think like a coach designing the architecture of a
week, not like a programmer filling slots.

Rules:
  - The user's days_per_week is the number of TRAINING days. Add recovery
    days on top ONLY if the user explicitly asks for them (preferences
    field). Otherwise just emit training days.
  - Respect injury constraints when deciding which muscles to train on
    which days (e.g. shoulder injury → no overhead-emphasis days early in
    the week; let the user rest into them).
  - Order days for recovery: don't train the same primary muscle group on
    back-to-back days. If recovery days are present, sequence them so
    training+recovery alternation looks reasonable.
  - day_index is the calendar slot (1 = Monday, 2 = Tuesday, ...). Recovery
    days take slots too.
  - Use the canonical muscle names from the schema enum, exactly.

End with a one-paragraph rationale explaining WHY this split for THIS user.
"""


def _constraints_block(constraints: list[str] | None) -> str:
    """Render standing constraints for injection into a build prompt.

    These are the distilled instructions from the user's past adjustments
    ("avoid X, my knee hurts"; "cut the volume"). They are NON-NEGOTIABLE —
    the user already asked for these, so the prompt frames them as hard
    requirements, not suggestions.
    """
    if not constraints:
        return ""
    lines = "\n".join(f"  - {c}" for c in constraints)
    return (
        "\n\nSTANDING CONSTRAINTS — the client has explicitly asked for these "
        "in the past. Honor every one of them; they override your default "
        "preferences:\n" + lines
    )


def plan_split(
    profile: UserProfile,
    llm: LLMClient,
    constraints: list[str] | None = None,
) -> WeekSplit:
    """Call 1 — LLM picks the weekly split. No catalog involved."""
    days_per_week = _coerce_int(profile.derived.get("days_per_week"), default=3)
    days_per_week = max(2, min(6, days_per_week))

    # Schema bound: at least training-days, up to 7 (one per calendar day).
    # The LLM decides how many recovery days to insert based on preferences.
    schema = _split_planner_schema(min_days=days_per_week, max_days=7)

    instruction = f"Produce {days_per_week} training days."
    # Detect preference for rest-day mobility. The intake "preferences" field
    # is free-text; we look for stretch/mobility/recovery cues. If present,
    # nudge the planner to schedule recovery days; otherwise omit them so the
    # plan stays focused on training.
    prefs = str(profile.derived.get("preferences") or profile.answers.get("preferences") or "")
    if any(kw in prefs.lower() for kw in ("stretch", "mobility", "recover", "yoga", "rest day")):
        rest_count = max(1, min(7 - days_per_week, 3))
        instruction += (
            f" The user prefers active recovery / stretching on rest days — "
            f"insert {rest_count} kind=recovery days between training days."
        )
    else:
        instruction += " Do NOT emit recovery days unless the user explicitly asked."

    user_msg = (
        "User profile:\n" + json.dumps(_profile_for_llm(profile), indent=2)
        + _constraints_block(constraints)
        + "\n\n" + instruction
    )
    raw = llm.complete_with_schema(
        SPLIT_PLANNER_SYSTEM,
        user_msg,
        schema,
        max_tokens=1500,
        task="SPLIT_PLANNER",
    )
    return WeekSplit.model_validate(raw)


# ---------------------------------------------------------------------------
# Exercise picker — Call 2 (per day).
# ---------------------------------------------------------------------------


def _picker_schema(candidate_names: list[str], min_count: int, max_count: int) -> dict[str, Any]:
    """Schema for one day's exercise picks. Catalog name is enum-constrained."""
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["exercises"],
        "properties": {
            "exercises": {
                "type": "array",
                "minItems": min_count,
                "maxItems": max_count,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["catalog_name", "slot", "rationale"],
                    "properties": {
                        "catalog_name": {
                            "type": "string",
                            "enum": candidate_names,
                        },
                        "slot": {"type": "string"},
                        "rationale": {"type": "string"},
                    },
                },
            },
        },
    }


PICKER_SYSTEM = """\
You are picking the exercises for ONE training day.

You will be given:
  - The day's target muscles and pattern focus
  - A user profile snippet (level, injuries, equipment, goal)
  - A CANDIDATES list — exercises we've already pre-filtered to match the
    user's equipment, the day's muscles, and the user's level

Pick 3-6 exercises from the CANDIDATES list. ONLY use exact names from
that list (the schema will reject anything else). Order them as you'd run
the session: heaviest compound first, accessories after.

Slot label conventions:
  - "primary_compound"   — the day's main lift (one of)
  - "secondary_compound" — a second compound, often a different angle
  - "accessory_N"        — isolation / smaller exercises, numbered

One-sentence rationale per pick — why THIS movement, not just "good chest
exercise". Reference the user's profile when relevant (injury, experience,
goal).
"""


def _filter_candidates(
    spec: DaySpec,
    catalog: ExerciseCatalog,
    available_equipment: set[str | None],
    level: str | None,
    limit: int = 60,
    avoided: set[str] | None = None,
) -> list[Exercise]:
    """Pre-filter the catalog down to a focused candidate set for one day.

    Strategy: union of finds across primary muscles, equipment-gated,
    level-gated. We deliberately allow secondary-muscle exercises too — a
    chest day wants flyes AND incline press AND triceps work. Capped at
    `limit` to stay well under OpenAI's enum size limits and keep prompts
    cheap.

    `avoided` is the set of lower-cased exercise names the user has asked us
    to stop prescribing. We drop them here so they never even reach the LLM —
    the user shouldn't have to see, much less re-reject, something they
    already vetoed.

    Level handling: include same-level and any-level (None level entries are
    stretches/cardio — let those through too).
    """
    avoided = avoided or set()
    seen: dict[str, Exercise] = {}

    # Pass 1 — strict level match, primary muscle hit.
    for muscle in spec.primary_muscles + spec.secondary_muscles:
        for ex in catalog.find(
            primary_muscle=muscle,
            equipment=available_equipment,
            level=level,
        ):
            seen.setdefault(ex.name.lower(), ex)

    # Pass 2 — any level, primary muscle hit. Backfills when level filter
    # is too strict (rare for beginner; common for "expert" where the
    # catalog has few entries).
    if len(seen) < 15:
        for muscle in spec.primary_muscles:
            for ex in catalog.find(
                primary_muscle=muscle,
                equipment=available_equipment,
            ):
                seen.setdefault(ex.name.lower(), ex)

    candidates = [ex for name, ex in seen.items() if name not in avoided]
    # Deterministic ordering — compound-first, then alphabetical — gives the
    # LLM a stable view and helps prompt caching.
    candidates.sort(key=lambda e: (e.mechanic != "compound", e.name))
    return candidates[:limit]


def pick_exercises_for_day(
    spec: DaySpec,
    profile: UserProfile,
    catalog: ExerciseCatalog,
    available_equipment: set[str | None],
    level: str | None,
    llm: LLMClient,
    constraints: list[str] | None = None,
    avoided: set[str] | None = None,
) -> DayPlan:
    """Call 2 — LLM picks 3-6 exercises for this one day from a filtered list."""
    candidates = _filter_candidates(
        spec, catalog, available_equipment, level, avoided=avoided,
    )
    if not candidates:
        logger.warning("ai_program.no_candidates day=%s muscles=%s",
                       spec.name, spec.primary_muscles)
        return DayPlan(spec=spec, exercises=[])

    candidate_names = [e.name for e in candidates]
    schema = _picker_schema(candidate_names, min_count=3, max_count=6)

    user_msg = (
        f"DAY: {spec.name}\n"
        f"primary_muscles: {spec.primary_muscles}\n"
        f"secondary_muscles: {spec.secondary_muscles}\n"
        f"pattern_focus: {spec.pattern_focus}\n"
        f"target_minutes: {spec.target_minutes}\n\n"
        f"USER PROFILE:\n{json.dumps(_profile_for_llm(profile), indent=2)}"
        + _constraints_block(constraints)
        + f"\n\nCANDIDATES (you MUST pick from this exact list):\n"
        + "\n".join(f"  - {n}" for n in candidate_names)
    )
    raw = llm.complete_with_schema(
        PICKER_SYSTEM,
        user_msg,
        schema,
        max_tokens=1200,
        task="EXERCISE_PICKER",
    )
    picks = [ExercisePick.model_validate(p) for p in raw.get("exercises", [])]
    return DayPlan(spec=spec, exercises=picks)


# ---------------------------------------------------------------------------
# Validation — deterministic, last line of defense.
# ---------------------------------------------------------------------------


def validate_plan(
    plan: DayPlan,
    catalog: ExerciseCatalog,
    available_equipment: set[str | None],
    avoided: set[str] | None = None,
) -> tuple[DayPlan, list[ValidationIssue]]:
    """Strip invalid picks, return cleaned plan + issue list.

    The schema already prevents most failures (catalog_name is enum-bound
    to a real catalog name from the candidate list). But there are classes
    of issue the schema can't catch:

      1. The candidate list itself was wrong (shouldn't happen, but
         defensive coding: re-verify equipment + muscle match).
      2. Duplicate picks within the day (the schema allows them).
      3. An avoided exercise slipped through — the user vetoed it, so it
         must never appear even if the picker somehow chose it.

    Issues are returned not raised — caller decides whether to retry,
    fall back to deterministic slot ladders, or just ship the partial day.
    """
    avoided = avoided or set()
    cleaned: list[ExercisePick] = []
    issues: list[ValidationIssue] = []
    seen_names: set[str] = set()

    target_muscles = {m.lower() for m in plan.spec.primary_muscles + plan.spec.secondary_muscles}

    for pick in plan.exercises:
        if pick.catalog_name.lower() in avoided:
            issues.append(ValidationIssue(
                day_index=plan.spec.day_index,
                catalog_name=pick.catalog_name,
                issue="avoided_by_user",
            ))
            continue
        ex = catalog.get(pick.catalog_name)
        if ex is None:
            issues.append(ValidationIssue(
                day_index=plan.spec.day_index,
                catalog_name=pick.catalog_name,
                issue="not_in_catalog",
            ))
            continue
        if ex.equipment not in available_equipment:
            issues.append(ValidationIssue(
                day_index=plan.spec.day_index,
                catalog_name=pick.catalog_name,
                issue="equipment_unavailable",
            ))
            continue
        ex_muscles = {m.lower() for m in ex.primary_muscles}
        # Cardiovascular-system "muscle" is whole-body — never fails this.
        if (
            target_muscles
            and "cardiovascular system" not in target_muscles
            and not (ex_muscles & target_muscles)
        ):
            issues.append(ValidationIssue(
                day_index=plan.spec.day_index,
                catalog_name=pick.catalog_name,
                issue="muscle_mismatch",
            ))
            continue
        key = pick.catalog_name.lower()
        if key in seen_names:
            issues.append(ValidationIssue(
                day_index=plan.spec.day_index,
                catalog_name=pick.catalog_name,
                issue="duplicate",
            ))
            continue
        seen_names.add(key)
        cleaned.append(pick)

    return DayPlan(spec=plan.spec, exercises=cleaned), issues


# ---------------------------------------------------------------------------
# Top-level orchestrator.
# ---------------------------------------------------------------------------


def build_program(
    profile: UserProfile,
    llm: LLMClient,
    catalog: ExerciseCatalog | None = None,
    parallel: bool = True,
    constraints: list[str] | None = None,
    avoided: set[str] | None = None,
) -> AIProgram:
    """End-to-end: split planner → per-day pickers (parallel) → validation.

    `parallel=True` runs the per-day exercise pickers concurrently. Cuts
    wall-clock from N*latency to ~1*latency. Safe because each picker call
    is independent.

    `constraints` are the user's standing adjustment instructions, injected
    into both the split-planner and exercise-picker prompts. `avoided` is the
    set of lower-cased exercise names the user has vetoed — filtered out of
    candidates AND hard-rejected at validation. Together these are how the
    coach "remembers" what the user told it.
    """
    cat = catalog or _default_catalog()
    available_equipment = cat.equipment_for_profile(profile.derived.get("equipment"))
    level = _coerce_level(profile.derived.get("experience"))

    split = plan_split(profile, llm, constraints=constraints)

    def _one(spec: DaySpec) -> DayPlan:
        # Recovery days don't go through the LLM — the renderer fills them
        # with stretches deterministically at session-render time. Saves an
        # LLM call per recovery day and keeps recovery prescriptions stable
        # across regenerations.
        if spec.kind == "recovery":
            return DayPlan(spec=spec, exercises=[])
        return pick_exercises_for_day(
            spec, profile, cat, available_equipment, level, llm,
            constraints=constraints, avoided=avoided,
        )

    if parallel and len(split.days) > 1:
        with ThreadPoolExecutor(max_workers=len(split.days)) as pool:
            day_plans = list(pool.map(_one, split.days))
    else:
        day_plans = [_one(d) for d in split.days]

    all_issues: list[ValidationIssue] = []
    validated: list[DayPlan] = []
    for plan in day_plans:
        if plan.spec.kind == "recovery":
            # Skip muscle/equipment validation for recovery days — their
            # picks are filled in at render time, not stored.
            validated.append(plan)
            continue
        clean, issues = validate_plan(plan, cat, available_equipment, avoided=avoided)
        validated.append(clean)
        all_issues.extend(issues)

    return AIProgram(split=split, days=validated, issues=all_issues)


# ---------------------------------------------------------------------------
# Small coercion helpers — UserProfile.derived is loose by design
# (LLM-shaped), so accessors are defensive.
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Rendering — convert an AIProgram day back into the existing Session shape
# that /session/next already returns. Lets us swap the LLM-picked exercises
# into the live flow without changing the iOS contract.
# ---------------------------------------------------------------------------


# Sets/reps per (goal_domain, slot_class). Lower reps + more sets for the
# main lift, higher reps + fewer sets for accessories. The LLM doesn't pick
# these — it only picks the exercise name and the slot label; numbers come
# from this table.
#
# slot_class is the leading word of the LLM's slot string ("primary_compound",
# "secondary_compound", "accessory_N", "stretch"). We coerce unknown slots
# to "accessory" so a wonky slot label still gets reasonable defaults.
_SETS_REPS: dict[tuple[str, str], tuple[int, int]] = {
    # strength — heavier and lower-rep across the board
    ("strength",     "primary"):   (5, 5),
    ("strength",     "secondary"): (3, 5),
    ("strength",     "accessory"): (3, 8),
    # hypertrophy — classic 8-12 range, more volume on accessories
    ("hypertrophy",  "primary"):   (4, 6),
    ("hypertrophy",  "secondary"): (4, 8),
    ("hypertrophy",  "accessory"): (3, 12),
    # conditioning / weight loss — moderate sets, higher reps to keep heart rate up
    ("conditioning", "primary"):   (3, 8),
    ("conditioning", "secondary"): (3, 10),
    ("conditioning", "accessory"): (3, 15),
    # longevity — gentle, volume over intensity
    ("longevity",    "primary"):   (3, 10),
    ("longevity",    "secondary"): (2, 12),
    ("longevity",    "accessory"): (2, 12),
    # discipline — 75-Hard style, lots of volume
    ("discipline",   "primary"):   (4, 8),
    ("discipline",   "secondary"): (3, 10),
    ("discipline",   "accessory"): (3, 12),
}


def _classify_slot(slot_label: str) -> str:
    """LLM slot label → one of {primary, secondary, accessory}.

    The picker prompt teaches the LLM to use slot strings like
    "primary_compound", "secondary_compound", "accessory_1". We look at the
    leading token. Unknown labels default to "accessory" (the safe choice —
    smaller load, won't hurt anyone).
    """
    head = slot_label.split("_", 1)[0].lower()
    if head == "primary":
        return "primary"
    if head == "secondary":
        return "secondary"
    return "accessory"


# Heuristic mapper from picked exercise name → canonical calibration slot.
# Used to derive a starting load from the user's measured 1RM when we can.
# Conservative: we'd rather return None and have the user feel out the
# weight than guess wrong and prescribe something dangerous. Order matters —
# more specific patterns must come before more generic ones (deadlift before
# squat etc.).
def _calibration_slot_for(exercise: Exercise) -> str | None:
    n = exercise.name.lower()
    pm = {m.lower() for m in exercise.primary_muscles}
    # Deadlift family — name match is reliable.
    if "deadlift" in n:
        return "deadlift"
    # Squat family — distinguish from leg press / split squat by primary muscle.
    if "squat" in n and "quadriceps" in pm:
        return "squat"
    # Bench family — must be a bench press, not a fly/extension.
    if "bench press" in n:
        return "bench"
    # Overhead press family.
    if ("military press" in n or "overhead press" in n
            or "shoulder press" in n or n.startswith("standing dumbbell press")):
        return "ohp"
    # Row family — barbell/dumbbell rows.
    if "row" in n and ("middle back" in pm or "lats" in pm):
        return "row"
    return None


# Scale factors per slot class — fraction of the canonical-slot working
# load to prescribe. Primary = full working load (whatever the persona's
# progression has earned). Secondary = lighter to manage fatigue. Accessory
# = even lighter, focus on tempo/control. Loads are rounded to the nearest
# 5 lb for plate practicality.
_LOAD_SCALE: dict[str, float] = {
    "primary":   1.00,
    "secondary": 0.85,
    "accessory": 0.70,
}


def _load_for_pick(
    exercise: Exercise,
    slot_class: str,
    progression: dict[str, float | int],
) -> float | None:
    """Best-effort load. None for unmappable picks — user fills it in."""
    slot = _calibration_slot_for(exercise)
    if slot is None:
        return None
    canonical = progression.get(f"{slot}_lb")
    if canonical is None:
        return None
    scaled = float(canonical) * _LOAD_SCALE.get(slot_class, 0.70)
    # Round to nearest 5 lb so the prescription reads like a real plate load.
    return round(scaled / 5) * 5


def render_session_from_ai_program(
    ai_program: "AIProgram",
    session_index: int,
    goal_domain: str,
    progression: dict[str, float | int],
    fallback: Session,
) -> Session:
    """Convert one day of the AIProgram into the existing Session shape.

    session_index rotates through the days array. The fallback is used when
    the AIProgram has nothing for this day (validation stripped it) or this
    day is a recovery day with no training exercises — caller still gets a
    valid Session.

    Sets/reps come from the (goal, slot_class) table. Loads come from the
    persona's progression dict (calibration-derived) when the picked
    exercise maps to a canonical slot; otherwise None (user enters weight
    themselves at log time).
    """
    if not ai_program.days:
        return fallback
    day = ai_program.days[session_index % len(ai_program.days)]

    # Recovery day → render the canned stretching block. No fallback to the
    # persona session here, because the recovery day exists *as* the day —
    # we don't want to overlay a strength session on top.
    if day.spec.kind == "recovery":
        return _render_recovery_session(day)

    if not day.exercises:
        return fallback

    rxs: list[ExercisePrescription] = []
    from .exercises import catalog as _cat
    cat = _cat()
    for pick in day.exercises:
        slot_class = _classify_slot(pick.slot)
        sets, reps = _SETS_REPS.get((goal_domain, slot_class), (3, 10))
        ex = cat.get(pick.catalog_name)
        load = _load_for_pick(ex, slot_class, progression) if ex else None
        rxs.append(ExercisePrescription(
            name=pick.catalog_name,
            sets=sets,
            reps=reps,
            load_lb=load,
            notes=pick.rationale,
        ))
    return Session(
        name=day.spec.name,
        summary=f"AI-built · {day.spec.pattern_focus}",
        expected_minutes=day.spec.target_minutes,
        progression_rule=fallback.progression_rule,
        exercises=rxs,
    )


def _render_recovery_session(day: "DayPlan") -> Session:
    """Stretches + mobility for a non-training day.

    Picks come from the catalog's stretching category, deterministically
    chosen to hit common tight areas (hips, hamstrings, t-spine, shoulders).
    No LLM call needed — stretching routines don't benefit much from
    personalization at this layer.
    """
    from .exercises import catalog as _cat
    cat = _cat()
    target_muscles = ["hamstrings", "quadriceps", "glutes", "lats", "chest"]
    picks: list[ExercisePrescription] = []
    seen: set[str] = set()
    for muscle in target_muscles:
        for ex in cat.find(category="stretching", primary_muscle=muscle):
            key = ex.name.lower()
            if key in seen:
                continue
            seen.add(key)
            picks.append(ExercisePrescription(
                name=ex.name,
                sets=1,
                reps=1,
                load_lb=None,
                notes=ex.first_instruction() or "Hold the stretch, breathe slow.",
                duration_min=1,
            ))
            break
        if len(picks) >= 5:
            break
    return Session(
        name=day.spec.name or "Recovery & Mobility",
        summary=f"Active recovery · {day.spec.pattern_focus or 'mobility'}",
        expected_minutes=day.spec.target_minutes,
        progression_rule="Hold each stretch ~60 seconds. No bouncing. Stop if anything sharp.",
        exercises=picks,
    )


def _coerce_int(v: Any, default: int) -> int:
    if isinstance(v, int):
        return v
    if isinstance(v, str) and v.strip().isdigit():
        return int(v.strip())
    return default


def _coerce_level(v: Any) -> str | None:
    """Map free-text experience → catalog level vocabulary."""
    if not v:
        return None
    s = str(v).lower()
    if "advanced" in s or "expert" in s:
        return "expert"
    if "intermediate" in s or "1+" in s or "2+" in s:
        return "intermediate"
    if "novice" in s or "beginner" in s or "new" in s or "none" in s:
        return "beginner"
    return None
